#!/usr/bin/python3

print("CREATE VIRTUAL TABLE gear_index USING rtree(")
print("    id,")
print("    minX, maxX,")
print("    minY, maxY,")
print("    +number,")
print(");")

import re
import sys

symbolRe = re.compile("[*]")
numberRe = re.compile("[0-9]+")

total = 0
with open(sys.argv[1], 'r') as file:
    lineno = 0
    for line in file.readlines():
        line = line.strip()
        for match in numberRe.finditer(line):
            # define the box
            top = lineno-1
            left = match.start()-1
            bottom = lineno+1
            right = match.end()

            number = int(match.group())
            print("INSERT INTO gear_index VALUES(NULL, %d, %d, %d, %d, %d);" % (top, bottom, left, right, number))

        lineno += 1

print(".mode json")
with open(sys.argv[1], 'r') as file:
    lineno = 0
    for line in file.readlines():
        line = line.strip()
        for match in symbolRe.finditer(line):
            column = match.span()[0]
            print("SELECT number FROM gear_index WHERE minX <= %d AND %d <= maxX and minY <= %d AND %d <= maxY;" % (lineno, lineno, column, column))
        lineno += 1
